version: '2'

services:

    webapp:
        image: scieloorg/search-journals
        restart: always
        hostname: webapp
        ports:
            - "80:80"
        environment:
            - SEARCH_FROM_MAIL=
            - SEARCH_SMTP_SERVER=
            - SEARCH_SMTP_PORT=
